### ISSUE TITLE
Support runtime / dynamic bloom sizing

### ISSUE THREAD

**Issue by walkah** [wnfs-wg/deterministic-bloom#4]
# Summary

## Problem

Bloom Filter sizes are currently pre-defined - for CAR mirror (e.g.) we'll want to be able to dynamically pick a size. 

### Impact

Limited sizes - determined at compile time - for all bloom filters created by this library.

## Solution

Allow for dynamic bloom filter sizing. (As @matheus23 pointed out: https://github.com/wnfs-wg/deterministic-bloom/pull/2#issuecomment-1443465381 )

**Comment by matheus23** [comment]
Let me go ahead and grab this item
